/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleConfidentialiteRouteImport } from './routes/$locale/confidentialite'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as AdminBlogNewRouteImport } from './routes/admin/blog/new'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as AdminBlogEditIdRouteImport } from './routes/admin/blog/edit.$id'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleConfidentialiteRoute = LocaleConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AdminBlogEditIdRoute = AdminBlogEditIdRouteImport.update({
  id: '/blog/edit/$id',
  path: '/blog/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$locale/confidentialite': typeof LocaleConfidentialiteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$locale/confidentialite': typeof LocaleConfidentialiteRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$locale/confidentialite': typeof LocaleConfidentialiteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/blog/edit/$id': typeof AdminBlogEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/confidentialite'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/admin/blog/new'
    | '/$locale/blog/'
    | '/admin/blog/'
    | '/admin/blog/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$locale/confidentialite'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/admin/blog/new'
    | '/$locale/blog'
    | '/admin/blog'
    | '/admin/blog/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/confidentialite'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/admin/blog/new'
    | '/$locale/blog/'
    | '/admin/blog/'
    | '/admin/blog/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/confidentialite': {
      id: '/$locale/confidentialite'
      path: '/confidentialite'
      fullPath: '/$locale/confidentialite'
      preLoaderRoute: typeof LocaleConfidentialiteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/blog/edit/$id': {
      id: '/admin/blog/edit/$id'
      path: '/blog/edit/$id'
      fullPath: '/admin/blog/edit/$id'
      preLoaderRoute: typeof AdminBlogEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleConfidentialiteRoute: typeof LocaleConfidentialiteRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleConfidentialiteRoute: LocaleConfidentialiteRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminBlogEditIdRoute: typeof AdminBlogEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminBlogEditIdRoute: AdminBlogEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
